services:
  flask:
    image: flask
    build: app
    volumes:
      - ./app/src:/app/src
    environment:
      DEPLOY_ENV: debug
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASS: password
      DATABASE_SCHEMA: app
    depends_on:
      - postgres

  postgres:
    image: "docker.io/postgres:16"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app

  nginx:
    image: nginx
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - flask
